// Mapeo flexible de rutas a las claves de permisos del sistema de Naguanagua
export const ROUTE_PERMISSIONS_MAP: Record<string, string[]> = {
  '/admin/administrativo': ['solo_administrador'],
  '/admin/administracion': ['solo_administrador'],
  '/admin/tarifas': ['ver_tarifas'],
  '/admin/censo': ['ver_censo', 'registrar_censo'],
  '/admin/contribuyentes': ['ver_contribuyentes', 'ver_contribuyentes_lectura', 'ver_caja', 'gestionar_pagos'],
  '/admin/condominios-cob': ['ver_condominios', 'cobro_masivo_condo'],
  '/admin/condominios': ['ver_condominios', 'cobro_masivo_condo'],
  '/admin/pre-registros': ['ver_pre_registros'],
  '/admin/jornadas': ['planificar_jornadas'],
  '/admin/ambiental': ['gestionar_visto_bueno'],
  '/admin/herramientas': ['ver_reportes'],
  '/admin/calculo': ['usar_calculadora_deuda'],
  '/admin/simulador': ['usar_calculadora_deuda', 'ver_caja', 'gestionar_pagos'],
  '/admin/caja': ['ver_caja', 'gestionar_pagos'],
  '/admin/caja/conciliacion': ['ver_conciliacion'],
  '/admin/facturacion-electronica': ['emitir_recibos', 'ver_caja'],
  '/admin/estado-cuenta': ['ver_estado_cuenta', 'descargar_pdf_ec', 'ver_caja'],
  '/admin/convenios-pago': ['ver_convenios'],
  '/admin/certificados': ['ver_certificados', 'emitir_solvencia', 'ver_caja'],
  '/admin/historial-documentos': ['ver_reportes', 'ver_certificados'],
  '/admin/buzon': ['ver_buzon'],
  '/admin/denuncias': ['ver_denuncias'],
  '/admin/rutas': ['ver_rutas'],
  '/admin/servicios-especiales': ['ver_servicios_especiales'],
  '/admin/reportes': ['ver_reportes', 'ver_caja'],
  '/admin/recibo-demo': ['ver_caja', 'ver_reportes'],
  '/admin/correos': ['ver_correos'],
  '/admin/trabajadores': ['gestionar_usuarios'],
  '/admin/auditoria': ['ver_auditoria'],
  '/admin/plan-accion': ['ver_rutas', 'planificar_jornadas'],
  '/cobro-movil': ['ver_caja', 'gestionar_pagos'],
};
